### ISSUE TITLE
Nominate command should not accept the target rank as a parameter

### ISSUE THREAD

**Issue by jrusbatch** [discord-csharp/MODiX#162]
**Story**

As a user, I would like to nominate another user for the next rank in the line of progression without needing to specify what that rank is when nominating them.

**Comment by JakenVeina** [comment]
Not sure why I didn't consider this myself, since the service ENFORCES that promotions go in order of rank, and can't skip over any ranks. So, at any given time, there is only one rank that a user could be promoted to (with the exception of the top rank, which has no possible promotions).

However, since this does remove a kind of implicit sanity check upon the user, such that they KNOW which rank they're nominating a user for, I think if we remove the parameter, we should add a "confirmation" to this command, where MODiX responds with a "You are nominating user X for promotion to rank Y" and the user is given a chance to confirm, before the campaign is officially created.
