### ISSUE TITLE
Allow a user to remove the result of a MODiX command

### ISSUE THREAD

**Issue by tannergooding** [discord-csharp/MODiX#299]
In some scenarios (such `!eval`) a user might have MODiX run a command that results in a response being posted to the channel. Sometimes you might have a small typo or something else and it can quickly cause the chat to "bloat" and an admin has to do the appropriate cleanup.

It would be useful if the submitter of a MODiX command could `react` with a particular emoji that would cause MODiX to remove the result. This would help ensure that users can cleanup their own mistakes where applicable.

**Comment by tannergooding** [comment]
The alternative is for users to just test their commands in `#bot-spam`, but I don't think people will actually do that in practice 😄

**Comment by Gnbrkm41** [comment]
For some codes that is pretty simple and expect to just work™ I sometimes do `!eval` directly in that channel, which turns out to have some syntax errors and things like that so I repeat it a few times in the channel causing nastiness. I started just doing that in `#bot-spam` then `!quote` it in the original channel so that's no problem for me, but some other people seems to do the same as well.

I personally agree with this.

**Comment by jrusbatch** [comment]
I think this is a good idea. Something short would be good. Maybe `:x:`?

**Comment by jrusbatch** [comment]
Would this be applied to all command output from MODiX? Or limited to results of `!eval`?

**Comment by tannergooding** [comment]
> Would this be applied to all command output from MODiX? Or limited to results of `!eval`?

I think `!eval` is probably the "most worthy". There are probably others as well, but it should likely be a case by case basis.
