### ISSUE TITLE
Consider whitelisting links to certain guilds?

### ISSUE THREAD

**Issue by Gnbrkm41** [discord-csharp/MODiX#435]
Certain guilds (e.g. Unity official server, discord.gg/unity) are less likely to be used as a way to advertise something; Maybe we could add some servers to a whitelist so they do not get removed by MODiX automatically when posted. What I can think of would be guilds like Discord.NET API guild and so on.

**Comment by Sutarodo** [comment]
While I don't see this is a huge change to the behavior for this, I'm not the work involved equates to usefulness. For official/useful invites, we could make the invite publicly available, like Unity in the game dev channel.

**Comment by JakenVeina** [comment]
Or putting them in a `!tag`.

**Comment by Inzanit** [comment]
I think the tag system is perfect for invites that are useful. If we didn't do this, we'd need to hit the database yet again to check for valid invites every time one is sent. I think there's also precedent to say, utilising the tag mechanism is better since the invite comes from MODiX rather than a random user.

I'll close this out for now, since there's a good mechanism in place to allow for invites to other guilds and it hasn't really been an issue.

Can be reopened if there is high demand for this.
