### ISSUE TITLE
Associates Can't See Promotions Page

### ISSUE THREAD

**Issue by joshuaedwardcrowe** [discord-csharp/MODiX#516]
Associates cant see the promotion page despite the decision being that they couldn't see *comments* on the active promotions.

**Comment by Scott-Caldwell** [comment]
To expand on this, this appears to be a new feature request for MODiX to have a separate claim for viewing the campaigns page vs viewing the comments on a campaign. For context, a recent administrative decision in the C# guild prompted the removal of the `PromotionsRead` claim from Associates, in an effort to prevent bandwagoning.

An implementation of this proposal would likely:
- Create a new claim specific to viewing comments on campaigns.
- Hide comments in the website from the view of users who do not have the claim.
- Always show the user's own comment in the website, regardless of whether they have the claim, so that they will still be able to edit their comment if necessary.
- Potentially hide the approval percentage of an active campaign from users who do not have the claim. This would apply to both the command and the website. For transparency, it would likely be a good idea to allow users without the claim to see the approval percentage after the campaign is closed.

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
