### ISSUE TITLE
Channel permissions are not checked before attempting permission override

### ISSUE THREAD

**Issue by Inzanit** [discord-csharp/MODiX#567]
See below. Exceptions throw when we try and access channels that the bot does not have access to manage permissions in (or even see). This should probably be handled more gracefully for UX perspective.

```
An exception was thrown when attempting to set up the mute role "MODiX_Moderation_Mute" for guild "C#", channel #"mod-log". This is likely due to Modix not having the "Manage Permissions" permission - please check your server settings.
The server responded with error 403: Forbidden
```

**Comment by Scott-Caldwell** [comment]
I've thought about this, and I think we'd have to be careful.

We could just check whether we have permission to manage the channel and, if not, just fail silently or log to the console. But I'd be worried about the possibility of having a channel where we would want Modix to be able to apply the mute, but someone misconfigured the permissions and Modix can't. In that case, the exception is actually beneficial, because it prompts us fix the channel configuration.

At minimum, though, I think it doesn't make sense for Modix to try to apply permission overrides to channels that it can't even see. So we should at least check for that.

For channels that Modix *can* see but for which we don't want mutes to apply anyway, we could check whether the channel is designated as `Unmoderated`. The concern there is that the `Unmoderated` designation has currently been bastardized for other uses, such as determining whether messages in the channel are eligible to be on the starboard. If we add a check for the `Unmoderated` designation to resolve this issue, I'd like it if we added a new `StarboardEligible` or `StarboardIneligible` designation first. (Or maybe we could use `CountsTowardsParticipation` for starboard as well. Might need to think on the implications of that.)

**Comment by Inzanit** [comment]
Opened up #568 to rectify problem.

**Comment by Inzanit** [comment]
Looks like we'll also need to filter out news channels, if possible. 

`News channels do not support Overwrite Permissions.`

**Comment by Inzanit** [comment]
Opened #573 to unblock issue
