### ISSUE TITLE
Add feature to reformat code by reaction

### ISSUE THREAD

**Issue by sabihoshi** [discord-csharp/MODiX#582]
I think it'd be a good feature to be able to reformat code easily by placing a certain reaction to it, just as how TL;DR works.
Most of the time, users don't un-indent their code.
<table>
<tr>
<th>
Before
</th>
<th>
After
</th>
</tr>

<tr>

<td>
<pre>
public void Foo()
            {
                // Bar
                if(foo) 
                { 
                }
            }
</pre>
</td>

<td>
<pre>
public void Foo()
{
    // Bar
    if(foo) { }
}
</pre>
</td>

</tr>
</table>

**Comment by Cisien** [comment]
iirc, roslyn gives the ability to apply formatting changes to code. I'm not sure how effective it will be in this limited context, though

**Comment by Scott-Caldwell** [comment]
We removed tl;dr, because it caused issues. It was a bit jarring to people to have their code reuploaded by the bot, and the straw that broke the camel's back was when people would react with tl;dr to Xero's #guild-feed posts.

I would rather not go through that again, so if we were to consider this, it would have to be done with considerable care not to reintroduce the same problems that tl;dr had.

**Comment by nucombo** [comment]
Shouldn't this be a feature suggestion to discord rather than MODiX then?

**Comment by Cisien** [comment]
you're delusional if you think discord's going to implement this. They barely support syntax highlighting!

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
