### ISSUE TITLE
Revisit !info optimisation

### ISSUE THREAD

**Issue by patrickklaeren** [discord-csharp/MODiX#617]
Currently `!info` performs a number of queries to accumulate info about a user when requested. These queries are run sequentially as of #616, as parallel (ongoing) queries cannot be executed on the same Entity Framework context.

This results in `!info` taking upwards of a second before it returns a usable embed to the user in Discord.

Look at possible optimisations in code, any caching we could do against the user/info itself and any further improvements to speed up the command.

Code in question:

https://github.com/discord-csharp/MODiX/blob/master/Modix.Bot/Modules/UserInfoModule.cs#L69-L168

**Comment by jmazouri** [comment]
Caching is a good solution, but what to cache and where to cache it is harder. Memory is easiest, but that could potentially add up - we'd need to ensure we use time or size based expiration liberally.

As far as initial performance, we could develop multiple flags to the command that return different levels of data - one with basic user info, one with guild participation, one with infractions (for staff), etc.

Alternatively (or in conjunction with the above), we could also provide the information asynchronously. Send out an initial response with the most basic / fastest to retrieve data, then fire up a task for each subsequent piece of info and edit the embed every time one of those tasks complete. Synchronization could be a bit of an issue, but it could be done sequentially as well. Also would need to make sure that we don't keep too many parallel operations working, and that we don't edit messages too frequently (though probably D.Net will handle that).

**Comment by FiniteReality** [comment]
I don't think caching will help in this case, unless you want to calculate the user's rank in the C# code instead of in a single query, since caching would necessarily imply loading the entire dataset to be useful.

If the single SQL query was retained then it would only be usable for a single user, and, well, a single user doesn't really query their info that often, do they?

**Comment by Cisien** [comment]
there's a broader issue that I suspect is caused by the database scale of our current plan. In the coming months I'll be doing work to migrate this to something that has better I/O perf.

Before we do too much more work on optimizing this command, we should wait until this is done.

If anything, effort should be made to improve the infractions performance first, since that's a much simpler set of operations, and is much more embarrassing if it fails, or is perceived to fail

**Comment by JakenVeina** [comment]
I still say I could give a fuck about this particular command being slow. It's very nature is to accumulate and summarize a LOT of data about a user, it should be expected to be slow, and we should provide UX enhancements to account for that. I.E. some indication of a "processing" state for the command.

**Comment by JakenVeina** [comment]
For the record, there was already an open issue for this. #696. However, since all the conversation is now here, I'll close that one.
