### ISSUE TITLE
SearchInfractions query is not translateable, after .NET Core 3.0 upgrade.

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#630]
Well, I'm assuming it's because of the upgrade, because it certainly used to work, and there are a variety of queries that broke on account of the upgrade, since EF now treats untranslateable queries as an error by default, rather than a warning.

https://paste.mod.gg/haboyerule

**Comment by NullEntity** [comment]
https://github.com/discord-csharp/MODiX/blob/0f64e6550b02432f609360eb9f54f330c1097bf6/Modix.Data/Models/Moderation/InfractionSearchCriteria.cs#L92
I did some testing and it looks like EF won't translate interpolated strings nor the calls to the OrdinalContains function. If this is replaced with string concat and Contains, the query is able to be translated and run on the server. I don't know how ordinal stuff applies when running the query on the db. Is using Contains instead of OrdinalContains fine for these EF queries?

**Comment by Scott-Caldwell** [comment]
It'd be ideal if we could find a way to make Contains case-insensitive, since I think this is for a username search box

**Comment by Inzanit** [comment]
I actually can't replicate this?

**Comment by Scott-Caldwell** [comment]
To repro, you can go to the site -> Logs -> Infractions, and try to filter on Subject or Creator
