### ISSUE TITLE
Improve user searching

### ISSUE THREAD

**Issue by spixy** [discord-csharp/MODiX#701]
Improve searching in [mod.gg/userlookup](https://mod.gg/userlookup).

1. allow searching for users with just 1 or 2 letter usernames?

![image](https://user-images.githubusercontent.com/4542110/73585240-a1026900-449f-11ea-878c-66cd010daae1.png)

2. fix searching result not including user who surely exists

![image](https://user-images.githubusercontent.com/4542110/73585172-d5295a00-449e-11ea-9fba-a811cd0c7e3d.png)

**Comment by JakenVeina** [comment]
1. That's probably a good idea, but we should make sure this isn't gonna put too much load on the DB or anything, trying to query that large of a resultset.

2. The issue here is that the list is limited to only the first 10 matches. There's definitely a match for "ther#6028", it's just sorted farther down, so you don't see it. And the only way you could further qualify the search would be by adding a "#", which the search algorithm doesn't support. For this, we should A) add support for discriminator searching, whether by specifying it via "#", or with a separate search box, and B) probably have the results sorted by match rank, which is something the database should support natively as part of its text search API. Dunno if this would be directly supported in EF.

**Comment by jmazouri** [comment]
> B) probably have the results sorted by match rank, which is something the database should support natively as part of its text search API. Dunno if this would be directly supported in EF.

A rudimentary solution would be to check both the equivalent of Contains() and StartsWith() in the query, and sort by StartsWith first. Shouldn't be too much more expensive but could be difficult to express in EF.

**Comment by spixy** [comment]
```cs
.Where(...)
.Select(user => new
{
    StartsWith = user.Username.StartsWith(query),
    Model = ModixUser.FromIGuildUser(user)
})
.OrderByDescending(x => x.StartsWith)
.Take(10)
.Select(x => x.Model);
```

should be enough (and its compillable)

**Comment by JakenVeina** [comment]
Addendum...

```cs
.OrderByDescending(x => x.StartsWith)
.ThenBy(x => x.Model.Username)
```

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
