### ISSUE TITLE
MODiX doesn't maintain spoilers when linking to a message containing an embed

### ISSUE THREAD

**Issue by tannergooding** [discord-csharp/MODiX#705]
If linking to a message which was spoilered and contains an embed, the embed will no longer be spoilered when MODiX creates it's own new embed.

This is particularly problematic for NSFW content.

**Comment by tannergooding** [comment]
![image](https://user-images.githubusercontent.com/10487869/73887535-9e49a000-4820-11ea-8ecb-2a28917acd7c.png)

**Comment by Cisien** [comment]
gotta protect that community standup!

**Comment by FiniteReality** [comment]
Something I mentioned to tanner while he was reproing this:
- Ignore any spoilered attachments (they start with `SPOILER_`) and ignore images in embeds if the message is spoilered
- Instead just link to the message and say "this message contains spoilered content" or something

Alternatively, if you want to use attachments, you can do this:
- Get the stream of the image
- Upload it in the message as an attachment with the name `SPOILER_<someHash>.<format>`
- Reference it as `attachment://SPOILER_<theHash>.<format>` instead of the image url
