### ISSUE TITLE
Unexpected output from the repl, returns "json" instead of an empty string

### ISSUE THREAD

**Issue by Atulin** [discord-csharp/MODiX#868]
![image](https://user-images.githubusercontent.com/11233299/117175273-f29a5180-adce-11eb-9a3f-6edfb0d54269.png)
https://discord.com/channels/143867839282020352/610909097897754665/839536721619058738

**Comment by Scott-Caldwell** [comment]
I'm surprised we haven't logged an issue for this already; it's a known bug.

It shows up as "json" because we format the response in a code block like
```json
<result>
```
But since the result is an empty string, Discord formats that as a regular code block with the word "json" as its content. We should check to see whether the repl result is null or whitespace and, if so, don't try to format as a json block.

**Comment by Hamsterland** [comment]
Same result if you try 

!eval
\```
\```
