### ISSUE TITLE
Implement Message Logging

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#909]
That is, implement tracking of message deletions and edits.

Only designated channels should be monitored. Or should only designated channels be excluded?

I like the idea of logging to a webhook, instead of a designated channel. Anyone else?

Should probably also include configurable auto-pruning of the channel.

Per-guild config options:
 - output channel/webhook
 - settings for auto-pruning
 - opt-in/opt-out behavior?

**Comment by Scott-Caldwell** [comment]
Include vs exclude
* I'd say exclude (i.e. log every channel by default). That way you don't have to remember to update the config every time you add a new channel to the server. Unlogged channels should be the minority.

Webhook vs designated channel
* I definitely like the webhook idea. The channel designation always felt awkward to me, because even though you could in theory add multiple channels under the MessageLog designation, it would be pretty strange to actually do so. So I'd say all the "logging" type channels (message, moderation, promotion, user profile update if we add it, etc.) would just be per-guild configs with only one webhook per log type per guild. They can all point to the same webhook or different, however the server manager wants to set it up.

Auto-pruning
* How do you mean? As in deleting old log messages? I'm not sure I see the purpose
