### ISSUE TITLE
Implement Infractions Tracking

### ISSUE THREAD

**Issue by JakenVeina** [discord-csharp/MODiX#911]
Start with just the framework for TRACKING infractions in the database. That includes ban tracking, via the Discord Audit Log.

Keep in mind that we'll need to be able to transfer data over from the current system. There probably at least needs to be a note column of some kind in which we can mention that infractions were imported. Unless we can embed that in the Reason/Description column. Or we could have a separate table that just attaches import source info to infraction IDs.

The Infractions system also needs to include a better searching UI in the Web Client, from the get-go.

**Comment by Scott-Caldwell** [comment]
This feature (and also a feature with the capability to run moderation commands like warn, mute, ban) will need to be implemented in order for the C# server to go live with threads, as Discord.Net does not support threads (and likely will not for some time).

Since threads will be generally available on August 17, the request is to have this implemented before then if possible.

**Comment by Scott-Caldwell** [comment]
For database schema, do we anticipate any major differences between the 1.0 infractions tables and 2.0? If not, it might be nice to try to import the existing infractions roughly as is

**Comment by JakenVeina** [comment]
I don't see the schema being very different, no. And definitely, will be planning to migrate data.
